sudo: requireed

services:
        - docker

before_install:
        - docker build -t a4illusionist/react-app -f Dockerfile.dev .

script:
        - docker run a4illusionist/react-app npm run test -- --coverage
