sudo: requireed

services:
        - docker

before_install:
        - docker build -t a4illusionist/react-app -f Dockerfile.dev .

script:
        - docker run a4illusionist/react-app npm run test -- --coverage

deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker-reactapp"
        env: "DockerReactapp-env"
        bucket_name: "elasticbeanstalk-us-east-2-979543503306"
        bucket_path: "docker-reactapp"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
